# Site settings
title: Programming Fitness
email: t.v.horan@gmail.com
description: My Blog 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.tomhoran.net" # the base hostname & protocol for your site
twitter_username: supertom44
github_username:  supertom44

# Build settings
markdown: kramdown
